### PR TITLE
Add support for Django 2.0

### PR DESCRIPTION
**Pull request by michael-k**
Closes django-statsd/django-statsd#95

### CODE REVIEW

**Comment by michael-k** [comment]
ping @xordoquy

**Comment by michael-k** [comment]
ping @xordoquy 

Sorry to be so annoying.  Our test logs are full with deprecation warnings and we're planning to move to Django 2.0 as soon as it's released.  Only 3 months to go and we'd hate to move to a fork.  3 month is not very long, considering that the first PR updating the middleware was created one year ago.

**Comment by xordoquy** [comment]
Sorry for the lag.
Looks good, thanks a lot for the work !

**Comment by michael-k** [comment]
Nice! Can you make a new release?

**Comment by xordoquy** [comment]
Will do in the next hour or so.

**Comment by xordoquy** [comment]
Done. Let me know how it goes :)

**Comment by michael-k** [comment]
We ran some tests on stage and everything worked fine; we're updating all our microservices on production now :)

**Pull request merged**
