### PR TITLE
Run tests against Django 2.0

### PR DESCRIPTION
**Pull request by michael-k**
https://www.djangoproject.com/weblog/2017/dec/02/django-20-released/

### CODE REVIEW

**Comment by xordoquy** [comment]
Thanks for your contribution. Looks good, looking forward to the CI to finish.

**Comment by michael-k** [comment]
py3.3 + Django 1.8 failed; I have no idea why

But Python 3.3 reached its EOL anyway: https://www.python.org/dev/peps/pep-0398/#x-end-of-life

**Comment by xordoquy** [comment]
Seems py.test has dropped the support of python 3.3 (https://github.com/pytest-dev/py/issues/175)
I'll remove that entry.

**Comment by xordoquy** [comment]
Thanks for the PR !

**Pull request merged**
